import ast
import base64
import json
import re
from urllib.parse import quote

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError
from odoo.tools import sql

from ..const import (
    AGGREGATE_NUMERIC_FIELD_TYPES,
    ALLOWED_FIELD_TYPES,
    BLOCK_SOURCE_FIELD_TYPES,
    DYNAMIC_REPORT_NAME_PREFIX,
    FORMULA_FIELD_TYPES,
    GROUP_FIELD_TYPES,
    PAPERFORMAT_VALUES,
    PAPERFORMAT_XML_IDS,
    REPORT_TEMPLATE_XML_ID,
)


HEX_COLOR_RE = re.compile(r"^#[0-9A-Fa-f]{6}$")
FORMULA_CODE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
CONCAT_TOKEN_SPLIT_RE = re.compile(r"[\s,;+]+")
ALLOWED_FORMULA_BINOPS = (ast.Add, ast.Sub, ast.Mult, ast.Div)
ALLOWED_FORMULA_UNARYOPS = (ast.UAdd, ast.USub)
ALLOWED_FORMULA_CMPOPS = (ast.Eq, ast.NotEq, ast.Lt, ast.LtE, ast.Gt, ast.GtE)
ALLOWED_FORMULA_NODES = (
    ast.Expression,
    ast.BinOp,
    ast.UnaryOp,
    ast.Compare,
    ast.Call,
    ast.Name,
    ast.Load,
    ast.Constant,
)
COLOR_FIELDS = (
    "primary_color",
    "secondary_color",
    "text_color",
    "table_header_bg_color",
    "table_header_text_color",
    "border_color",
)
STYLE_DEFAULTS = {
    "layout_style": "classic",
    "paper_size": "a4",
    "direction": "ltr",
    "primary_color": "#875A7B",
    "secondary_color": "#F3F4F6",
    "text_color": "#111827",
    "table_header_bg_color": "#875A7B",
    "table_header_text_color": "#FFFFFF",
    "border_color": "#D1D5DB",
    "font_size": 12,
    "title_font_size": 22,
    "show_company_logo": True,
    "show_company_name": True,
    "show_report_title": True,
    "show_footer": True,
    "footer_text": "Generated by Dynamic PDF Report Builder",
    "show_print_date": True,
    "show_page_number": True,
    "table_border_style": "solid",
    "zebra_rows": True,
    "template_preset": False,
}
TEMPLATE_PRESET_VALUES = {
    "classic_business": {
        "layout_style": "classic",
        "direction": "ltr",
        "primary_color": "#875A7B",
        "table_header_bg_color": "#875A7B",
        "table_border_style": "solid",
    },
    "modern_clean": {
        "layout_style": "modern",
        "primary_color": "#2563EB",
        "secondary_color": "#F8FAFC",
        "table_header_bg_color": "#2563EB",
        "table_border_style": "light",
    },
    "arabic_rtl": {
        "direction": "rtl",
        "layout_style": "modern",
        "primary_color": "#0F766E",
        "table_header_bg_color": "#0F766E",
        "show_company_logo": True,
    },
    "minimal_light": {
        "layout_style": "minimal",
        "primary_color": "#111827",
        "table_header_bg_color": "#111827",
        "table_border_style": "none",
        "zebra_rows": False,
    },
    "invoice_style": {
        "layout_style": "classic",
        "show_company_logo": True,
        "show_company_name": True,
        "show_footer": True,
    },
}


class DynamicPdfReport(models.Model):
    _name = "dynamic.pdf.report"
    _description = "Dynamic PDF Report"
    _order = "name, id"

    name = fields.Char(required=True)
    model_id = fields.Many2one(
        "ir.model",
        required=True,
        ondelete="cascade",
        domain=[("transient", "=", False)],
    )
    model_name = fields.Char(
        string="Technical Model Name",
        related="model_id.model",
        store=True,
        readonly=True,
    )
    report_title = fields.Char()
    preview_record_limit = fields.Integer(
        string="Preview Record Limit",
        default=20,
        help="Maximum number of recent records included when previewing a grouped report.",
    )
    field_line_ids = fields.One2many("dynamic.pdf.report.field", "report_id")
    line_section_ids = fields.One2many("dynamic.pdf.report.line.section", "report_id")
    block_ids = fields.One2many("dynamic.pdf.report.block", "report_id")
    formula_ids = fields.One2many(
        "dynamic.pdf.report.formula",
        "report_id",
        context={"active_test": False},
    )
    group_ids = fields.One2many("dynamic.pdf.report.group", "report_id")
    aggregate_ids = fields.One2many("dynamic.pdf.report.aggregate", "report_id")
    report_action_id = fields.Many2one(
        "ir.actions.report",
        readonly=True,
        copy=False,
    )
    state = fields.Selection(
        [("draft", "Draft"), ("done", "Done")],
        default="draft",
        required=True,
    )
    layout_style = fields.Selection(
        [("classic", "Classic"), ("modern", "Modern"), ("minimal", "Minimal")],
        default="classic",
        required=True,
    )
    paper_size = fields.Selection(
        [("a4", "A4"), ("a5", "A5")],
        default="a4",
        required=True,
    )
    direction = fields.Selection(
        [("ltr", "Left to Right"), ("rtl", "Right to Left")],
        default="ltr",
        required=True,
    )
    primary_color = fields.Char(default="#875A7B", required=True)
    secondary_color = fields.Char(default="#F3F4F6", required=True)
    text_color = fields.Char(default="#111827", required=True)
    table_header_bg_color = fields.Char(default="#875A7B", required=True)
    table_header_text_color = fields.Char(default="#FFFFFF", required=True)
    border_color = fields.Char(default="#D1D5DB", required=True)
    font_size = fields.Integer(default=12, required=True)
    title_font_size = fields.Integer(default=22, required=True)
    show_company_logo = fields.Boolean(default=True)
    show_company_name = fields.Boolean(default=True)
    show_report_title = fields.Boolean(default=True)
    show_footer = fields.Boolean(default=True)
    footer_text = fields.Char(default="Generated by Dynamic PDF Report Builder")
    show_print_date = fields.Boolean(default=True)
    show_page_number = fields.Boolean(default=True)
    table_border_style = fields.Selection(
        [("none", "None"), ("solid", "Solid"), ("light", "Light")],
        default="solid",
        required=True,
    )
    zebra_rows = fields.Boolean(default=True)
    template_preset = fields.Selection(
        [
            ("classic_business", "Classic Business"),
            ("modern_clean", "Modern Clean"),
            ("arabic_rtl", "Arabic RTL"),
            ("minimal_light", "Minimal Light"),
            ("invoice_style", "Invoice Style"),
        ],
        string="Template Preset",
    )
    last_generated_on = fields.Datetime(readonly=True, copy=False)
    last_generated_by = fields.Many2one("res.users", readonly=True, copy=False)
    print_count = fields.Integer(readonly=True, default=0, copy=False)
    last_printed_on = fields.Datetime(readonly=True, copy=False)
    last_printed_by = fields.Many2one("res.users", readonly=True, copy=False)
    print_log_count = fields.Integer(compute="_compute_print_log_count")

    def _compute_print_log_count(self):
        PrintLog = self.env["dynamic.pdf.report.print.log"].sudo()
        for report in self:
            report.print_log_count = PrintLog.search_count([("report_id", "=", report.id)]) if report.id else 0

    @api.onchange("model_id")
    def _onchange_model_id(self):
        if self.field_line_ids:
            self.field_line_ids = False
        if self.line_section_ids:
            self.line_section_ids = False
        if self.group_ids:
            self.group_ids = False
        if self.aggregate_ids:
            self.aggregate_ids = False
        for block in self.block_ids:
            block.source_field_id = False
        for formula in self.formula_ids:
            formula.line_section_id = False

    @api.constrains("model_id")
    def _check_report_model(self):
        for report in self:
            if report.model_id.transient:
                raise ValidationError(_("You cannot create dynamic PDF reports for transient models."))

    @api.constrains(
        "model_id",
        "field_line_ids",
        "line_section_ids",
        "block_ids",
        "formula_ids",
        "group_ids",
        "aggregate_ids",
    )
    def _check_field_lines_match_model(self):
        for report in self:
            wrong_lines = report.field_line_ids.filtered(
                lambda line: line.field_id and line.field_id.model_id != report.model_id
            )
            if wrong_lines:
                raise ValidationError(_("All selected fields must belong to the selected model."))
            wrong_sections = report.line_section_ids.filtered(
                lambda section: section.one2many_field_id and section.one2many_field_id.model_id != report.model_id
            )
            if wrong_sections:
                raise ValidationError(_("All line sections must use One2many fields from the selected model."))
            wrong_blocks = report.block_ids.filtered(
                lambda block: block.source_field_id and block.source_field_id.model_id != report.model_id
            )
            if wrong_blocks:
                raise ValidationError(_("All block source fields must belong to the selected model."))
            wrong_formulas = report.with_context(active_test=False).formula_ids.filtered(
                lambda formula: formula.line_section_id and formula.line_section_id.report_id != report
            )
            if wrong_formulas:
                raise ValidationError(_("All line-section formulas must use sections from the same report."))
            wrong_groups = report.group_ids.filtered(
                lambda group: group.field_id and group.field_id.model_id != report.model_id
            )
            if wrong_groups:
                raise ValidationError(_("All grouping fields must belong to the selected model."))
            wrong_aggregates = report.aggregate_ids.filtered(
                lambda aggregate: aggregate.field_id and aggregate.field_id.model_id != report.model_id
            )
            if wrong_aggregates:
                raise ValidationError(_("All aggregate fields must belong to the selected model."))

    @api.constrains(*COLOR_FIELDS)
    def _check_hex_colors(self):
        for report in self:
            report._validate_hex_colors()

    @api.constrains("preview_record_limit")
    def _check_preview_record_limit(self):
        for report in self:
            if not 1 <= (report.preview_record_limit or 0) <= 100:
                raise ValidationError(_("Preview Record Limit must be between 1 and 100."))

    def action_create_report(self):
        for report in self:
            report._validate_report_configuration()
            action = report._get_or_create_report_action()
            report.write({
                "report_action_id": action.id,
                "state": "done",
                "last_generated_on": fields.Datetime.now(),
                "last_generated_by": self.env.user.id,
            })
        return True

    def action_apply_template(self):
        for report in self:
            if not report.template_preset:
                raise UserError(_("Select a template preset before applying a template."))
            report.write(dict(TEMPLATE_PRESET_VALUES[report.template_preset]))
        return True

    def action_suggest_report_structure(self):
        self.ensure_one()
        self._check_suggestion_assistant_access()
        if not self.id:
            raise UserError(_("Save the report before using the Smart Report Assistant."))
        if not self.model_id:
            raise UserError(_("Select a model before using the Smart Report Assistant."))

        wizard = self.env["dynamic.pdf.report.suggestion.wizard"].create({
            "report_id": self.id,
        })
        wizard._generate_suggestions()
        return {
            "type": "ir.actions.act_window",
            "name": _("Suggest Report Structure"),
            "res_model": "dynamic.pdf.report.suggestion.wizard",
            "res_id": wizard.id,
            "view_mode": "form",
            "views": [(
                self.env.ref("dynamic_pdf_report_builder.view_dynamic_pdf_report_suggestion_wizard_form").id,
                "form",
            )],
            "target": "new",
        }

    def _check_suggestion_assistant_access(self):
        if not self.env.user.has_group("base.group_system"):
            raise UserError(_("Only Settings users can use the Smart Report Assistant."))

    def action_open_print_logs(self):
        self.ensure_one()
        if not self.env.user.has_group("base.group_system"):
            raise UserError(_("Only Settings users can view dynamic report print logs."))
        action = self.env.ref("dynamic_pdf_report_builder.action_dynamic_pdf_report_print_log").read()[0]
        action["domain"] = [("report_id", "=", self.id)]
        action["context"] = {
            "default_report_id": self.id,
        }
        return action

    def action_reset_styling(self):
        for report in self:
            report.write(dict(STYLE_DEFAULTS))
        return True

    def action_preview_report(self):
        self.ensure_one()
        self._validate_preview_configuration()
        self._validate_report_configuration()
        action = self._get_or_create_report_action()
        self.write({
            "report_action_id": action.id,
            "state": "done",
            "last_generated_on": fields.Datetime.now(),
            "last_generated_by": self.env.user.id,
        })

        preview_records = self._get_preview_records()
        context = {
            "dynamic_pdf_report_id": self.id,
            "dynamic_pdf_report_source": "preview",
        }
        return {
            "type": "ir.actions.act_url",
            "url": "/report/pdf/%s/%s?context=%s" % (
                action.report_name,
                ",".join(str(record_id) for record_id in preview_records.ids),
                quote(json.dumps(context)),
            ),
            "target": "self",
        }

    def action_duplicate_design(self):
        self.ensure_one()
        if not self.id:
            raise UserError(_("Save the report before duplicating the design."))

        new_report = self.create(self._prepare_duplicate_design_vals())
        self._copy_duplicate_formulas(new_report)
        return {
            "type": "ir.actions.act_window",
            "name": _("Copy of %s", self.name),
            "res_model": self._name,
            "res_id": new_report.id,
            "view_mode": "form",
            "target": "current",
        }

    def action_export_template(self):
        self.ensure_one()
        self._check_template_export_access()
        payload = self._prepare_export_template_payload()
        json_content = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False).encode("utf-8")
        filename = self._get_export_template_filename()
        attachment = self.env["ir.attachment"].create({
            "name": filename,
            "type": "binary",
            "datas": base64.b64encode(json_content).decode("ascii"),
            "res_model": self._name,
            "res_id": self.id,
            "mimetype": "application/json",
        })
        return {
            "type": "ir.actions.act_url",
            "url": "/web/content/%s?download=true" % attachment.id,
            "target": "self",
        }

    def _check_template_export_access(self):
        if not self.env.user.has_group("base.group_system"):
            raise UserError(_("Only Settings users can export dynamic report templates."))

    def _prepare_export_template_payload(self):
        self.ensure_one()
        return {
            "version": "1.0",
            "module": "dynamic_pdf_report_builder",
            "report": self._prepare_export_report_data(),
            "fields": self._prepare_export_field_data(),
            "line_sections": self._prepare_export_line_section_data(),
            "blocks": self._prepare_export_block_data(),
            "formulas": self._prepare_export_formula_data(),
            "groups": self._prepare_export_group_data(),
            "aggregates": self._prepare_export_aggregate_data(),
        }

    def _prepare_export_report_data(self):
        self.ensure_one()
        return {
            "name": self.name,
            "report_title": self.report_title,
            "model": self.model_name,
            "preview_record_limit": self.preview_record_limit,
            "styling": {
                field_name: self[field_name]
                for field_name in STYLE_DEFAULTS
            },
        }

    def _prepare_export_field_data(self):
        self.ensure_one()
        return [
            {
                "sequence": line.sequence,
                "field_name": line.field_name,
                "show_label": line.show_label,
            }
            for line in self.field_line_ids.sorted("sequence")
            if line.field_name
        ]

    def _prepare_export_line_section_data(self):
        self.ensure_one()
        return [
            {
                "sequence": section.sequence,
                "name": section.name,
                "one2many_field_name": section.one2many_field_name,
                "show_section_title": section.show_section_title,
                "line_fields": [
                    {
                        "sequence": line.sequence,
                        "field_name": line.field_name,
                        "show_label": line.show_label,
                    }
                    for line in section.line_field_ids.sorted("sequence")
                    if line.field_name
                ],
            }
            for section in self.line_section_ids.sorted("sequence")
            if section.one2many_field_name
        ]

    def _prepare_export_block_data(self):
        self.ensure_one()
        return [
            {
                "sequence": block.sequence,
                "block_type": block.block_type,
                "title": block.title,
                "content": block.content,
                "position": block.position,
                "alignment": block.alignment,
                "is_active": block.is_active,
                "source_type": block.source_type,
                "source_field_name": block.source_field_id.name if block.source_field_id else False,
                "static_value": block.static_value,
                "custom_url_prefix": block.custom_url_prefix,
                "barcode_type": block.barcode_type,
                "size_preset": block.size_preset,
                "size": block.size,
                "signature_label": block.signature_label,
                "signer_name": block.signer_name,
                "signer_position": block.signer_position,
                "show_signature_line": block.show_signature_line,
                "watermark_text": block.watermark_text,
                "watermark_opacity": block.watermark_opacity,
            }
            for block in self.block_ids.sorted("sequence")
        ]

    def _prepare_export_formula_data(self):
        self.ensure_one()
        formulas = self.with_context(active_test=False).formula_ids.sorted("sequence")
        return [
            {
                "sequence": formula.sequence,
                "name": formula.name,
                "code": formula.code,
                "scope": formula.scope,
                "line_section_field_name": (
                    formula.line_section_id.one2many_field_name
                    if formula.line_section_id else False
                ),
                "formula_type": formula.formula_type,
                "active": formula.active,
                "formula_expression": formula.formula_expression,
                "separator": formula.separator,
                "condition_expression": formula.condition_expression,
                "true_value": formula.true_value,
                "false_value": formula.false_value,
                "output_label": formula.output_label,
                "show_in_report": formula.show_in_report,
                "show_in_line_tables": formula.show_in_line_tables,
            }
            for formula in formulas
        ]

    def _prepare_export_group_data(self):
        self.ensure_one()
        return [
            {
                "sequence": group.sequence,
                "field_name": group.field_name,
            }
            for group in self.group_ids.sorted("sequence")
            if group.field_name
        ]

    def _prepare_export_aggregate_data(self):
        self.ensure_one()
        return [
            {
                "field_name": aggregate.field_name,
                "aggregate_type": aggregate.aggregate_type,
            }
            for aggregate in self.aggregate_ids
            if aggregate.field_name
        ]

    def _get_export_template_filename(self):
        self.ensure_one()
        model_part = (self.model_name or "model").replace(".", "_")
        name_part = re.sub(r"[^a-zA-Z0-9_]+", "_", self.name or "report").strip("_").lower()
        name_part = name_part or "report"
        return "dynamic_report_template_%s_%s.json" % (model_part, name_part)

    def _validate_preview_configuration(self):
        self.ensure_one()
        if not self.model_id:
            raise UserError(_("Select a model before previewing this report."))
        if not self.field_line_ids.filtered("field_id"):
            raise UserError(_("Add at least one field before previewing this report."))

    def _get_preview_record(self):
        self.ensure_one()
        active_model = self.env.context.get("active_model")
        active_ids = self.env.context.get("active_ids") or []
        active_id = self.env.context.get("active_id")
        if active_id and active_id not in active_ids:
            active_ids = [active_id] + active_ids

        record = self.env[self.model_name]
        if active_model == self.model_name and active_ids:
            record = self.env[self.model_name].browse(active_ids[:1]).exists()
        if not record:
            records = self.env[self.model_name].search([], limit=50)
            record = self._get_preview_record_with_line_data(records) or records[:1]
        if not record:
            raise UserError(_("No records found to preview this report."))
        return record

    def _get_preview_records(self):
        self.ensure_one()
        if not self.group_ids:
            return self._get_preview_record()

        limit = min(max(self.preview_record_limit or 20, 1), 100)
        active_model = self.env.context.get("active_model")
        active_ids = self.env.context.get("active_ids") or []
        active_id = self.env.context.get("active_id")
        if active_id and active_id not in active_ids:
            active_ids = [active_id] + active_ids
        if active_model == self.model_name and active_ids:
            records = self.env[self.model_name].browse(active_ids).exists()[:limit]
            if records:
                return records

        records = self.env[self.model_name].search([], order="id desc", limit=limit)
        if not records:
            raise UserError(_("No records found to preview this report."))
        return records

    def _get_preview_record_with_line_data(self, records):
        self.ensure_one()
        if not self.line_section_ids or not records:
            return records.browse()

        scored_records = []
        for record in records:
            line_count = 0
            for section in self.line_section_ids:
                field_name = section.one2many_field_name
                if field_name and field_name in record._fields:
                    line_count += len(record[field_name])
            if line_count:
                scored_records.append((line_count, record.id, record))
        if not scored_records:
            return records.browse()
        return min(scored_records, key=lambda item: (item[0], item[1]))[2]

    def _prepare_duplicate_design_vals(self):
        self.ensure_one()
        vals = {
            "name": _("Copy of %s", self.name),
            "model_id": self.model_id.id,
            "report_title": self.report_title,
            "preview_record_limit": self.preview_record_limit,
            "state": "draft",
            "report_action_id": False,
            "last_generated_on": False,
            "last_generated_by": False,
        }
        for field_name in STYLE_DEFAULTS:
            vals[field_name] = self[field_name]
        vals["field_line_ids"] = [
            (0, 0, {
                "field_id": line.field_id.id,
                "sequence": line.sequence,
                "show_label": line.show_label,
            })
            for line in self.field_line_ids.sorted("sequence")
            if line.field_id
        ]
        vals["line_section_ids"] = [
            (0, 0, {
                "name": section.name,
                "one2many_field_id": section.one2many_field_id.id,
                "sequence": section.sequence,
                "show_section_title": section.show_section_title,
                "line_field_ids": [
                    (0, 0, {
                        "field_id": line.field_id.id,
                        "sequence": line.sequence,
                        "show_label": line.show_label,
                    })
                    for line in section.line_field_ids.sorted("sequence")
                    if line.field_id
                ],
            })
            for section in self.line_section_ids.sorted("sequence")
            if section.one2many_field_id
        ]
        vals["block_ids"] = [
            (0, 0, {
                "sequence": block.sequence,
                "block_type": block.block_type,
                "title": block.title,
                "content": block.content,
                "position": block.position,
                "alignment": block.alignment,
                "is_active": block.is_active,
                "source_type": block.source_type,
                "source_field_id": block.source_field_id.id,
                "static_value": block.static_value,
                "custom_url_prefix": block.custom_url_prefix,
                "barcode_type": block.barcode_type,
                "size_preset": block.size_preset,
                "size": block.size,
                "signature_label": block.signature_label,
                "signer_name": block.signer_name,
                "signer_position": block.signer_position,
                "show_signature_line": block.show_signature_line,
                "watermark_text": block.watermark_text,
                "watermark_opacity": block.watermark_opacity,
            })
            for block in self.block_ids.sorted("sequence")
        ]
        vals["group_ids"] = [
            (0, 0, {
                "sequence": group.sequence,
                "field_id": group.field_id.id,
            })
            for group in self.group_ids.sorted("sequence")
            if group.field_id
        ]
        vals["aggregate_ids"] = [
            (0, 0, {
                "field_id": aggregate.field_id.id,
                "aggregate_type": aggregate.aggregate_type,
            })
            for aggregate in self.aggregate_ids
            if aggregate.field_id
        ]
        return vals

    def _copy_duplicate_formulas(self, new_report):
        self.ensure_one()
        section_map = {}
        for section in self.line_section_ids:
            new_section = new_report.line_section_ids.filtered(
                lambda line_section, section=section: line_section.one2many_field_id == section.one2many_field_id
            )[:1]
            if new_section:
                section_map[section.id] = new_section.id

        formula_commands = []
        for formula in self.with_context(active_test=False).formula_ids.sorted("sequence"):
            line_section_id = False
            if formula.scope == "line_section":
                line_section_id = section_map.get(formula.line_section_id.id)
                if not line_section_id:
                    continue
            formula_commands.append((0, 0, {
                "name": formula.name,
                "code": formula.code,
                "scope": formula.scope,
                "line_section_id": line_section_id,
                "formula_type": formula.formula_type,
                "sequence": formula.sequence,
                "active": formula.active,
                "formula_expression": formula.formula_expression,
                "separator": formula.separator,
                "condition_expression": formula.condition_expression,
                "true_value": formula.true_value,
                "false_value": formula.false_value,
                "output_label": formula.output_label,
                "show_in_report": formula.show_in_report,
                "show_in_line_tables": formula.show_in_line_tables,
            }))
        if formula_commands:
            new_report.with_context(active_test=False).write({"formula_ids": formula_commands})

    def _validate_report_configuration(self):
        self.ensure_one()
        if not self.model_id:
            raise UserError(_("Select a model before creating the report."))
        if self.model_id.transient:
            raise UserError(_("Transient models cannot be used for dynamic PDF reports."))
        if not self.model_name or self.model_name not in self.env:
            raise UserError(_("The selected model is not available in the registry."))
        self._validate_hex_colors()

        field_lines = self.field_line_ids.filtered("field_id")
        if not field_lines:
            raise UserError(_("Add at least one field before creating the report."))

        field_ids = field_lines.mapped("field_id").ids
        if len(field_ids) != len(set(field_ids)):
            raise UserError(_("A field can only be selected once in the same report."))

        invalid_lines = field_lines.filtered(lambda line: line.field_type not in ALLOWED_FIELD_TYPES)
        if invalid_lines:
            allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
            raise UserError(_("Phase 1 supports only these field types: %s", allowed_types))

        wrong_lines = field_lines.filtered(lambda line: line.field_id.model_id != self.model_id)
        if wrong_lines:
            raise UserError(_("All selected fields must belong to the selected model."))

        self._validate_line_sections()
        self._validate_blocks()
        self._validate_formulas()
        self._validate_groups_and_aggregates()

    def _validate_blocks(self):
        self.ensure_one()
        for block in self.block_ids:
            block._validate_block_configuration()

    def _validate_formulas(self):
        self.ensure_one()
        for formula in self.with_context(active_test=False).formula_ids:
            formula._validate_formula_configuration()

    def _validate_groups_and_aggregates(self):
        self.ensure_one()
        groups = self.group_ids.filtered("field_id")
        group_field_ids = groups.mapped("field_id").ids
        if len(group_field_ids) != len(set(group_field_ids)):
            raise UserError(_("A field can only be used once for grouping in the same report."))
        for group in groups:
            group._validate_group_configuration()

        aggregate_keys = []
        for aggregate in self.aggregate_ids.filtered("field_id"):
            aggregate._validate_aggregate_configuration()
            aggregate_keys.append((aggregate.field_id.id, aggregate.aggregate_type))
        if len(aggregate_keys) != len(set(aggregate_keys)):
            raise UserError(_("The same aggregate can only be configured once per report."))

    def _validate_line_sections(self):
        self.ensure_one()
        sections = self.line_section_ids
        if not sections:
            return

        section_field_ids = []
        for section in sections.sorted("sequence"):
            if not section.one2many_field_id:
                raise UserError(_("Line section '%s' must have a One2many field.", section.name or _("New")))
            if section.one2many_field_id.ttype != "one2many":
                raise UserError(
                    _("Line section '%s' must use a One2many field.", section.name or section.one2many_field_id.name)
                )
            if section.one2many_field_id.model_id != self.model_id:
                raise UserError(
                    _("Line section '%s' must use a One2many field from the selected report model.", section.name)
                )
            if not section.related_model_name or section.related_model_name not in self.env:
                raise UserError(
                    _("Line section '%s' has an invalid related model. Check the One2many field relation.", section.name)
                )

            section_field_ids.append(section.one2many_field_id.id)
            line_fields = self.env["dynamic.pdf.report.line.field"].search([
                ("section_id", "=", section.id),
                ("field_id", "!=", False),
            ])
            if not line_fields:
                raise UserError(_("Line section '%s' must contain at least one line field.", section.name))

            line_field_ids = line_fields.mapped("field_id").ids
            if len(line_field_ids) != len(set(line_field_ids)):
                raise UserError(_("Line section '%s' contains duplicate line fields.", section.name))

            invalid_fields = line_fields.filtered(lambda line: line.field_type not in ALLOWED_FIELD_TYPES)
            if invalid_fields:
                allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
                raise UserError(_("Line sections support only these field types: %s", allowed_types))

            wrong_fields = line_fields.filtered(lambda line: line.field_id.model_id != section.related_model_id)
            if wrong_fields:
                raise UserError(
                    _("All line fields in section '%s' must belong to the One2many related model.", section.name)
                )

        if len(section_field_ids) != len(set(section_field_ids)):
            raise UserError(_("A One2many field can only be used once in the same dynamic report."))

    def _get_or_create_report_action(self):
        self.ensure_one()
        ReportAction = self.env["ir.actions.report"].sudo()
        action = self.report_action_id.sudo().exists()
        if not action:
            action = ReportAction.search([("dynamic_pdf_report_id", "=", self.id)], limit=1)

        action_vals = self._prepare_report_action_vals()
        if action:
            action.write(action_vals)
        else:
            action = ReportAction.create(action_vals)
        return action

    def _prepare_report_action_vals(self):
        self.ensure_one()
        unique_report_name = "%s%s" % (DYNAMIC_REPORT_NAME_PREFIX, self.id)
        return {
            "name": self.name,
            "model": self.model_name,
            "report_type": "qweb-pdf",
            # Each action needs a unique route so Odoo's download controller
            # resolves the action that the user actually clicked. Rendering is
            # mapped back to the shared QWeb template by ir.actions.report.
            "report_name": unique_report_name,
            "report_file": unique_report_name,
            "binding_model_id": self.model_id.id,
            "binding_type": "report",
            "binding_view_types": "list,form",
            "context": "{'dynamic_pdf_report_id': %d, 'dynamic_pdf_report_source': 'print_menu'}" % self.id,
            "paperformat_id": self._get_paperformat().id,
            "dynamic_pdf_report_id": self.id,
        }

    def _validate_hex_colors(self):
        self.ensure_one()
        for field_name in COLOR_FIELDS:
            value = (self[field_name] or "").strip()
            if not HEX_COLOR_RE.match(value):
                field_label = self._fields[field_name].string
                raise UserError(_("%(field)s must be a valid hex color like #FFFFFF.", field=field_label))

    def _get_paperformat(self):
        self.ensure_one()
        paper_size = self.paper_size or "a4"
        xml_id = PAPERFORMAT_XML_IDS[paper_size]
        paperformat = self.env.ref(xml_id, raise_if_not_found=False)
        if paperformat:
            return paperformat

        values = dict(PAPERFORMAT_VALUES[paper_size])
        paperformat = self.env["report.paperformat"].sudo().search([("name", "=", values["name"])], limit=1)
        if paperformat:
            paperformat.write(values)
        else:
            paperformat = self.env["report.paperformat"].sudo().create(values)
        return paperformat


class DynamicPdfReportField(models.Model):
    _name = "dynamic.pdf.report.field"
    _description = "Dynamic PDF Report Field"
    _order = "sequence, id"

    _sql_constraints = [
        (
            "unique_report_field",
            "unique(report_id, field_id)",
            "A field can only be selected once in the same report.",
        ),
    ]

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    field_id = fields.Many2one("ir.model.fields", required=True, ondelete="cascade")
    field_name = fields.Char(related="field_id.name", store=True, readonly=True)
    field_description = fields.Char(related="field_id.field_description", store=True, readonly=True)
    field_type = fields.Selection(related="field_id.ttype", store=True, readonly=True)
    sequence = fields.Integer(default=10)
    show_label = fields.Boolean(default=True)

    @api.constrains("field_id", "report_id")
    def _check_field_id(self):
        for line in self:
            if line.field_id.model_id != line.report_id.model_id:
                raise ValidationError(_("The selected field must belong to the report model."))
            if line.field_type not in ALLOWED_FIELD_TYPES:
                allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
                raise ValidationError(_("Phase 1 supports only these field types: %s", allowed_types))


class DynamicPdfReportBlock(models.Model):
    _name = "dynamic.pdf.report.block"
    _description = "Dynamic PDF Report Visual Block"
    _order = "sequence, id"

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    sequence = fields.Integer(default=10)
    block_type = fields.Selection(
        [
            ("static_text", "Static Text"),
            ("terms_conditions", "Terms & Conditions"),
            ("signature", "Signature"),
            ("qr_code", "QR Code"),
            ("barcode", "Barcode"),
            ("watermark", "Watermark"),
            ("note", "Note"),
        ],
        required=True,
    )
    title = fields.Char()
    content = fields.Html(sanitize=True)
    position = fields.Selection(
        [
            ("before_main_table", "Before Main Table"),
            ("after_main_table", "After Main Table"),
            ("before_line_sections", "Before Line Sections"),
            ("after_line_sections", "After Line Sections"),
            ("footer_area", "Footer Area"),
        ],
        default="after_main_table",
        required=True,
    )
    alignment = fields.Selection(
        [
            ("left", "Left"),
            ("center", "Center"),
            ("right", "Right"),
            ("top_right", "Top Right"),
        ],
        default="left",
        required=True,
    )
    is_active = fields.Boolean(default=True)
    source_type = fields.Selection(
        [
            ("record_name", "Record Name"),
            ("field_value", "Field Value"),
            ("static_value", "Static Value"),
            ("custom_url", "Custom URL"),
        ],
        default="record_name",
        required=True,
    )
    source_field_id = fields.Many2one(
        "ir.model.fields",
        ondelete="cascade",
        domain=[("ttype", "in", BLOCK_SOURCE_FIELD_TYPES)],
    )
    static_value = fields.Char()
    custom_url_prefix = fields.Char()
    barcode_type = fields.Selection(
        [("Code128", "Code128")],
        default="Code128",
        required=True,
    )
    size_preset = fields.Selection(
        [
            ("small", "Small"),
            ("medium", "Medium"),
            ("large", "Large"),
            ("custom", "Custom"),
        ],
        default="medium",
        required=True,
    )
    size = fields.Integer(default=120)
    signature_label = fields.Char(default="Signature")
    signer_name = fields.Char()
    signer_position = fields.Char()
    show_signature_line = fields.Boolean(default=True)
    watermark_text = fields.Char(default="CONFIDENTIAL")
    watermark_opacity = fields.Float(default=0.08)

    @api.onchange("source_type")
    def _onchange_source_type(self):
        if self.source_type != "field_value":
            self.source_field_id = False

    @api.constrains(
        "report_id",
        "block_type",
        "source_type",
        "source_field_id",
        "static_value",
        "custom_url_prefix",
        "barcode_type",
        "size_preset",
        "size",
        "signature_label",
        "watermark_text",
        "watermark_opacity",
    )
    def _check_block_configuration(self):
        for block in self:
            block._validate_block_configuration(use_validation_error=True)

    def _validate_block_configuration(self, use_validation_error=False):
        self.ensure_one()
        error = ValidationError if use_validation_error else UserError

        if self.source_field_id:
            if self.source_field_id.ttype not in BLOCK_SOURCE_FIELD_TYPES:
                allowed_types = ", ".join(BLOCK_SOURCE_FIELD_TYPES)
                raise error(_("QR and barcode source fields support only these field types: %s", allowed_types))
            if self.report_id and self.source_field_id.model_id != self.report_id.model_id:
                raise error(_("The QR/barcode source field must belong to the selected report model."))

        if self.block_type in ("qr_code", "barcode"):
            if self.size_preset == "custom" and (self.size or 0) <= 0:
                raise error(_("QR code and barcode size must be greater than zero."))
            if self.source_type == "field_value" and not self.source_field_id:
                raise error(_("Select a source field for QR/barcode blocks using field value."))
            if self.source_type == "static_value" and not self.static_value:
                raise error(_("Enter a static value for QR/barcode blocks using static value."))
            if self.source_type == "custom_url" and not self.custom_url_prefix:
                raise error(_("Enter a custom URL prefix for QR/barcode blocks using custom URL."))

        if self.block_type == "signature" and not (self.signature_label or "").strip():
            raise error(_("Enter a signature label for signature blocks."))

        if self.block_type == "watermark" and not self.watermark_text:
            raise error(_("Enter watermark text for watermark blocks."))
        if self.block_type == "watermark" and not 0 <= self.watermark_opacity <= 1:
            raise error(_("Watermark opacity must be between 0 and 1."))


class DynamicPdfReportFormula(models.Model):
    _name = "dynamic.pdf.report.formula"
    _description = "Dynamic PDF Report Formula"
    _order = "sequence, id"

    _sql_constraints = [
        (
            "unique_report_formula_code",
            "unique(report_id, code)",
            "Formula code must be unique per report.",
        ),
    ]

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    name = fields.Char(required=True)
    code = fields.Char()
    scope = fields.Selection(
        [("main_record", "Main Record"), ("line_section", "Line Section")],
        default="main_record",
        required=True,
    )
    line_section_id = fields.Many2one(
        "dynamic.pdf.report.line.section",
        ondelete="cascade",
    )
    formula_type = fields.Selection(
        [
            ("arithmetic", "Arithmetic"),
            ("concat", "Concat"),
            ("conditional", "Conditional"),
        ],
        default="arithmetic",
        required=True,
    )
    sequence = fields.Integer(default=10)
    active = fields.Boolean(default=True)
    formula_expression = fields.Text()
    separator = fields.Char(default=" - ")
    condition_expression = fields.Text()
    true_value = fields.Char()
    false_value = fields.Char()
    output_label = fields.Char()
    show_in_report = fields.Boolean(default=True)
    show_in_line_tables = fields.Boolean(default=True)

    def init(self):
        if not sql.table_exists(self.env.cr, self._table) or not sql.column_exists(self.env.cr, self._table, "code"):
            return

        self.env.cr.execute(
            """
            SELECT id, report_id, COALESCE(name, ''), COALESCE(code, '')
              FROM dynamic_pdf_report_formula
             ORDER BY report_id, id
            """
        )
        rows = self.env.cr.fetchall()
        used_codes_by_report = {}
        for _formula_id, report_id, _name, code in rows:
            if code:
                used_codes_by_report.setdefault(report_id, set()).add(code)

        updates = []
        for formula_id, report_id, name, code in rows:
            if code:
                continue
            used_codes = used_codes_by_report.setdefault(report_id, set())
            updates.append((self._make_unique_formula_code_for_set(name or "formula", used_codes), formula_id))

        if updates:
            self.env.cr.executemany(
                "UPDATE dynamic_pdf_report_formula SET code = %s WHERE id = %s",
                updates,
            )

    @api.model_create_multi
    def create(self, vals_list):
        reserved_codes_by_report = {}
        prepared_vals_list = []
        for vals in vals_list:
            vals = dict(vals)
            self._prepare_formula_code_vals(vals, reserved_codes_by_report=reserved_codes_by_report)
            prepared_vals_list.append(vals)
        return super().create(prepared_vals_list)

    def write(self, vals):
        if self.env.context.get("skip_formula_code_autofill"):
            return super().write(vals)

        should_prepare_code = (
            "code" in vals
            or "report_id" in vals
            or "name" in vals
            or any(not formula.code for formula in self)
        )
        if not should_prepare_code:
            return super().write(vals)

        reserved_codes_by_report = {}
        for formula in self:
            formula_vals = dict(vals)
            if "code" in vals or "report_id" in vals or not formula.code:
                formula._prepare_formula_code_vals(
                    formula_vals,
                    formula=formula,
                    reserved_codes_by_report=reserved_codes_by_report,
                )
            super(DynamicPdfReportFormula, formula).write(formula_vals)
        return True

    @api.onchange("name")
    def _onchange_name_formula_code(self):
        for formula in self:
            if formula.name and not formula.code:
                formula.code = formula._slugify_formula_code(formula.name)

    @api.onchange("scope")
    def _onchange_scope(self):
        if self.scope != "line_section":
            self.line_section_id = False

    @api.constrains(
        "report_id",
        "name",
        "code",
        "scope",
        "line_section_id",
        "formula_type",
        "formula_expression",
        "condition_expression",
    )
    def _check_formula_configuration(self):
        for formula in self:
            formula._validate_formula_configuration(use_validation_error=True)

    def _validate_formula_configuration(self, use_validation_error=False):
        self.ensure_one()
        error = ValidationError if use_validation_error else UserError

        if not self.name:
            raise error(_("Formula name is required."))
        if not self.code:
            self._ensure_formula_code()
        if not FORMULA_CODE_RE.match(self.code or ""):
            raise error(_("Formula code must start with a letter or underscore and contain only letters, numbers, and underscores."))

        target_model_name = self._get_formula_target_model_name(error)
        if not target_model_name:
            return

        if self.formula_type == "arithmetic":
            expression = (self.formula_expression or "").strip()
            if not expression:
                raise error(_("Formula '%s' must have an arithmetic expression.", self.name))
            self._validate_safe_expression(expression, target_model_name, error, allow_compare=False)
            self._check_literal_division_by_zero(expression, error)
        elif self.formula_type == "concat":
            field_names = self._get_concat_field_names(error)
            if not field_names:
                raise error(_("Formula '%s' must list at least one field to concatenate.", self.name))
            self._validate_formula_field_names(field_names, target_model_name, error)
        elif self.formula_type == "conditional":
            expression = (self.condition_expression or "").strip()
            if not expression:
                raise error(_("Formula '%s' must have a condition expression.", self.name))
            self._validate_safe_expression(expression, target_model_name, error, allow_compare=True)
            self._check_literal_division_by_zero(expression, error)
        else:
            raise error(_("Formula '%s' has an invalid formula type.", self.name))

    def _get_formula_target_model_name(self, error):
        self.ensure_one()
        if not self.report_id:
            return False
        if self.scope == "main_record":
            if self.line_section_id:
                raise error(_("Main-record formula '%s' cannot be linked to a line section.", self.name))
            model_name = self.report_id.model_name
        elif self.scope == "line_section":
            if not self.line_section_id:
                raise error(_("Line-section formula '%s' must have a line section.", self.name))
            if self.line_section_id.report_id != self.report_id:
                raise error(_("Line-section formula '%s' must use a section from the same report.", self.name))
            model_name = self.line_section_id.related_model_name
        else:
            raise error(_("Formula '%s' has an invalid scope.", self.name))

        if not model_name or model_name not in self.env:
            raise error(_("Formula '%s' has an unavailable target model.", self.name))
        return model_name

    def _validate_safe_expression(self, expression, model_name, error, allow_compare=False):
        self.ensure_one()
        try:
            tree = ast.parse(expression, mode="eval")
        except SyntaxError as exception:
            raise error(_("Formula '%(formula)s' has invalid syntax: %(error)s", formula=self.name, error=exception.msg))

        parents = {
            child: parent
            for parent in ast.walk(tree)
            for child in ast.iter_child_nodes(parent)
        }
        field_names = set()
        for node in ast.walk(tree):
            if not isinstance(node, ALLOWED_FORMULA_NODES + ALLOWED_FORMULA_BINOPS + ALLOWED_FORMULA_UNARYOPS + ALLOWED_FORMULA_CMPOPS):
                raise error(_("Formula '%s' contains an unsupported expression.", self.name))
            if isinstance(node, ast.BinOp) and not isinstance(node.op, ALLOWED_FORMULA_BINOPS):
                raise error(_("Formula '%s' uses an unsupported operator.", self.name))
            if isinstance(node, ast.UnaryOp) and not isinstance(node.op, ALLOWED_FORMULA_UNARYOPS):
                raise error(_("Formula '%s' uses an unsupported unary operator.", self.name))
            if isinstance(node, ast.Compare):
                if not allow_compare:
                    raise error(_("Arithmetic formula '%s' cannot use comparison operators.", self.name))
                if any(not isinstance(operator, ALLOWED_FORMULA_CMPOPS) for operator in node.ops):
                    raise error(_("Formula '%s' uses an unsupported comparison operator.", self.name))
            if isinstance(node, ast.Call):
                if not isinstance(node.func, ast.Name) or node.func.id != "round" or node.keywords or len(node.args) not in (1, 2):
                    raise error(_("Formula '%s' can only call round(value[, digits]).", self.name))
            if isinstance(node, ast.Name):
                if node.id == "round":
                    parent = parents.get(node)
                    if not isinstance(parent, ast.Call) or parent.func is not node:
                        raise error(_("Formula '%s' can only use round as a function call.", self.name))
                else:
                    field_names.add(node.id)
            if isinstance(node, ast.Constant) and not isinstance(node.value, (int, float, str, bool, type(None))):
                raise error(_("Formula '%s' contains an unsupported literal value.", self.name))

        self._validate_formula_field_names(field_names, model_name, error)

    def _validate_formula_field_names(self, field_names, model_name, error):
        self.ensure_one()
        model_fields = self.env[model_name]._fields
        for field_name in field_names:
            if field_name not in model_fields:
                raise error(_("Formula '%(formula)s' references unknown field '%(field)s'.", formula=self.name, field=field_name))
            if model_fields[field_name].type not in FORMULA_FIELD_TYPES:
                allowed_types = ", ".join(FORMULA_FIELD_TYPES)
                raise error(
                    _("Formula '%(formula)s' field '%(field)s' has unsupported type. Supported types: %(types)s",
                      formula=self.name, field=field_name, types=allowed_types)
                )

    def _get_concat_field_names(self, error=ValidationError):
        self.ensure_one()
        expression = (self.formula_expression or "").strip()
        field_names = []
        for token in CONCAT_TOKEN_SPLIT_RE.split(expression):
            if not token:
                continue
            if not FORMULA_CODE_RE.match(token):
                raise error(_("Concat formula '%(formula)s' contains invalid field token '%(token)s'.", formula=self.name, token=token))
            field_names.append(token)
        return field_names

    def _check_literal_division_by_zero(self, expression, error):
        self.ensure_one()
        tree = ast.parse(expression, mode="eval")
        for node in ast.walk(tree):
            if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Div) and self._is_literal_zero(node.right):
                raise error(_("Formula '%s' divides by zero.", self.name))

    def _is_literal_zero(self, node):
        if isinstance(node, ast.Constant):
            return node.value == 0
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.UAdd, ast.USub)):
            return self._is_literal_zero(node.operand)
        return False

    def _prepare_formula_code_vals(self, vals, formula=False, reserved_codes_by_report=None):
        reserved_codes_by_report = reserved_codes_by_report if reserved_codes_by_report is not None else {}
        raw_code = vals.get("code")
        current_code = formula.code if formula else False
        should_generate = "code" not in vals or not (raw_code or "").strip()

        if not should_generate and raw_code == current_code and "report_id" not in vals:
            vals["code"] = raw_code
            return vals

        report_id = vals.get("report_id") or (formula.report_id.id if formula else False)
        base = vals.get("name") or (formula.name if formula else False) or raw_code or current_code or "formula"
        if not should_generate:
            base = raw_code

        reserved_codes = reserved_codes_by_report.setdefault(report_id or 0, set())
        vals["code"] = self._make_unique_formula_code(
            base,
            report_id,
            exclude_ids=formula.ids if formula else False,
            reserved_codes=reserved_codes,
        )
        return vals

    @api.model
    def _make_unique_formula_code(self, base, report_id=False, exclude_ids=False, reserved_codes=None):
        used_codes = set(reserved_codes or ())
        if report_id:
            domain = [("report_id", "=", report_id), ("code", "!=", False)]
            if exclude_ids:
                domain.append(("id", "not in", exclude_ids))
            used_codes.update(self.with_context(active_test=False).search(domain).mapped("code"))

        code = self._make_unique_formula_code_for_set(base, used_codes)
        if reserved_codes is not None:
            reserved_codes.add(code)
        return code

    @api.model
    def _make_unique_formula_code_for_set(self, base, used_codes):
        base_code = self._slugify_formula_code(base)
        code = base_code
        suffix = 2
        while code in used_codes:
            code = "%s_%s" % (base_code, suffix)
            suffix += 1
        used_codes.add(code)
        return code

    @api.model
    def _slugify_formula_code(self, value):
        code = (value or "").strip().lower()
        code = re.sub(r"[^a-z0-9_]+", "_", code)
        code = re.sub(r"_+", "_", code).strip("_")
        if not code:
            code = "formula"
        if not re.match(r"^[a-z_]", code):
            code = "formula_%s" % code
        return code

    def _ensure_formula_code(self):
        for formula in self:
            if formula.code:
                continue
            code = formula._make_unique_formula_code(
                formula.name or "formula",
                formula.report_id.id,
                exclude_ids=formula.ids,
            )
            formula.env.cr.execute(
                "UPDATE dynamic_pdf_report_formula SET code = %s WHERE id = %s",
                (code, formula.id),
            )
            formula.invalidate_recordset(["code"])


class DynamicPdfReportGroup(models.Model):
    _name = "dynamic.pdf.report.group"
    _description = "Dynamic PDF Report Group"
    _order = "sequence, id"

    _sql_constraints = [
        (
            "unique_report_group_field",
            "unique(report_id, field_id)",
            "A field can only be used once for grouping in the same report.",
        ),
    ]

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    sequence = fields.Integer(default=10)
    field_id = fields.Many2one(
        "ir.model.fields",
        required=True,
        ondelete="cascade",
        domain=[("ttype", "in", GROUP_FIELD_TYPES)],
    )
    field_name = fields.Char(related="field_id.name", store=True, readonly=True)
    field_description = fields.Char(related="field_id.field_description", store=True, readonly=True)
    field_type = fields.Selection(related="field_id.ttype", store=True, readonly=True)

    @api.model_create_multi
    def create(self, vals_list):
        self._validate_unique_group_fields(vals_list)
        return super().create(vals_list)

    def write(self, vals):
        checks = []
        for group in self:
            checks.append({
                "report_id": vals.get("report_id", group.report_id.id),
                "field_id": vals.get("field_id", group.field_id.id),
            })
        self._validate_unique_group_fields(checks, exclude_ids=self.ids)
        return super().write(vals)

    @api.model
    def _validate_unique_group_fields(self, vals_list, exclude_ids=None):
        keys = []
        for vals in vals_list:
            report_id = vals.get("report_id")
            field_id = vals.get("field_id")
            if report_id and field_id:
                keys.append((report_id, field_id))
        if len(keys) != len(set(keys)):
            raise ValidationError(_("A field can only be used once for grouping in the same report."))
        for report_id, field_id in keys:
            domain = [("report_id", "=", report_id), ("field_id", "=", field_id)]
            if exclude_ids:
                domain.append(("id", "not in", exclude_ids))
            if self.search_count(domain):
                raise ValidationError(_("A field can only be used once for grouping in the same report."))

    @api.constrains("field_id", "report_id")
    def _check_group_configuration(self):
        for group in self:
            group._validate_group_configuration(use_validation_error=True)

    def _validate_group_configuration(self, use_validation_error=False):
        self.ensure_one()
        error = ValidationError if use_validation_error else UserError
        if not self.field_id:
            raise error(_("Select a field to group by."))
        if self.report_id and self.field_id.model_id != self.report_id.model_id:
            raise error(_("Grouping field '%s' must belong to the selected report model.", self.field_description))
        if self.field_type not in GROUP_FIELD_TYPES:
            allowed_types = ", ".join(GROUP_FIELD_TYPES)
            raise error(_("Grouping supports only these field types: %s", allowed_types))


class DynamicPdfReportAggregate(models.Model):
    _name = "dynamic.pdf.report.aggregate"
    _description = "Dynamic PDF Report Aggregate"
    _order = "id"

    _sql_constraints = [
        (
            "unique_report_aggregate",
            "unique(report_id, field_id, aggregate_type)",
            "The same aggregate can only be configured once per report.",
        ),
    ]

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    field_id = fields.Many2one(
        "ir.model.fields",
        required=True,
        ondelete="cascade",
        domain=[("ttype", "in", ALLOWED_FIELD_TYPES)],
    )
    field_name = fields.Char(related="field_id.name", store=True, readonly=True)
    field_description = fields.Char(related="field_id.field_description", store=True, readonly=True)
    field_type = fields.Selection(related="field_id.ttype", store=True, readonly=True)
    aggregate_type = fields.Selection(
        [
            ("sum", "Sum"),
            ("count", "Count"),
            ("avg", "Average"),
            ("min", "Minimum"),
            ("max", "Maximum"),
        ],
        default="sum",
        required=True,
    )

    @api.model_create_multi
    def create(self, vals_list):
        self._validate_unique_aggregates(vals_list)
        return super().create(vals_list)

    def write(self, vals):
        checks = []
        for aggregate in self:
            checks.append({
                "report_id": vals.get("report_id", aggregate.report_id.id),
                "field_id": vals.get("field_id", aggregate.field_id.id),
                "aggregate_type": vals.get("aggregate_type", aggregate.aggregate_type),
            })
        self._validate_unique_aggregates(checks, exclude_ids=self.ids)
        return super().write(vals)

    @api.model
    def _validate_unique_aggregates(self, vals_list, exclude_ids=None):
        keys = []
        for vals in vals_list:
            report_id = vals.get("report_id")
            field_id = vals.get("field_id")
            aggregate_type = vals.get("aggregate_type", "sum")
            if report_id and field_id and aggregate_type:
                keys.append((report_id, field_id, aggregate_type))
        if len(keys) != len(set(keys)):
            raise ValidationError(_("The same aggregate can only be configured once per report."))
        for report_id, field_id, aggregate_type in keys:
            domain = [
                ("report_id", "=", report_id),
                ("field_id", "=", field_id),
                ("aggregate_type", "=", aggregate_type),
            ]
            if exclude_ids:
                domain.append(("id", "not in", exclude_ids))
            if self.search_count(domain):
                raise ValidationError(_("The same aggregate can only be configured once per report."))

    @api.constrains("field_id", "report_id", "aggregate_type")
    def _check_aggregate_configuration(self):
        for aggregate in self:
            aggregate._validate_aggregate_configuration(use_validation_error=True)

    def _validate_aggregate_configuration(self, use_validation_error=False):
        self.ensure_one()
        error = ValidationError if use_validation_error else UserError
        if not self.field_id:
            raise error(_("Select a field to aggregate."))
        if self.report_id and self.field_id.model_id != self.report_id.model_id:
            raise error(_("Aggregate field '%s' must belong to the selected report model.", self.field_description))
        if self.field_type not in ALLOWED_FIELD_TYPES:
            allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
            raise error(_("Aggregates support only these field types: %s", allowed_types))
        if self.aggregate_type in ("sum", "avg", "min", "max") and self.field_type not in AGGREGATE_NUMERIC_FIELD_TYPES:
            numeric_types = ", ".join(AGGREGATE_NUMERIC_FIELD_TYPES)
            raise error(
                _("Aggregate '%(aggregate)s' on '%(field)s' requires a numeric field. Supported types: %(types)s",
                  aggregate=self.aggregate_type, field=self.field_description, types=numeric_types)
            )


class DynamicPdfReportLineSection(models.Model):
    _name = "dynamic.pdf.report.line.section"
    _description = "Dynamic PDF Report Line Section"
    _order = "sequence, id"

    _sql_constraints = [
        (
            "unique_report_one2many_field",
            "unique(report_id, one2many_field_id)",
            "A One2many field can only be used once in the same dynamic report.",
        ),
    ]

    report_id = fields.Many2one(
        "dynamic.pdf.report",
        required=True,
        ondelete="cascade",
    )
    name = fields.Char(required=True)
    one2many_field_id = fields.Many2one(
        "ir.model.fields",
        required=True,
        ondelete="cascade",
        domain=[("ttype", "=", "one2many")],
    )
    one2many_field_name = fields.Char(
        string="One2many Technical Name",
        related="one2many_field_id.name",
        store=True,
        readonly=True,
    )
    related_model_id = fields.Many2one(
        "ir.model",
        compute="_compute_related_model",
        store=True,
        readonly=True,
    )
    related_model_name = fields.Char(
        compute="_compute_related_model",
        store=True,
        readonly=True,
    )
    line_field_ids = fields.One2many("dynamic.pdf.report.line.field", "section_id")
    sequence = fields.Integer(default=10)
    show_section_title = fields.Boolean(default=True)

    @api.depends("one2many_field_id.relation")
    def _compute_related_model(self):
        IrModel = self.env["ir.model"]
        for section in self:
            related_model = False
            if section.one2many_field_id.relation:
                related_model = IrModel.search([("model", "=", section.one2many_field_id.relation)], limit=1)
            section.related_model_id = related_model
            section.related_model_name = related_model.model if related_model else False

    @api.onchange("one2many_field_id")
    def _onchange_one2many_field_id(self):
        if self.one2many_field_id:
            if not self.name:
                self.name = self.one2many_field_id.field_description or self.one2many_field_id.name
            if self.line_field_ids:
                self.line_field_ids = False

    @api.constrains("one2many_field_id", "report_id", "related_model_id")
    def _check_one2many_field_id(self):
        for section in self:
            if not section.report_id or not section.one2many_field_id:
                continue
            if section.one2many_field_id.ttype != "one2many":
                raise ValidationError(_("Line sections must use One2many fields."))
            if section.one2many_field_id.model_id != section.report_id.model_id:
                raise ValidationError(_("The One2many field must belong to the selected report model."))
            if not section.related_model_id or section.related_model_name not in self.env:
                raise ValidationError(_("The selected One2many field has an invalid relation model."))
            wrong_fields = section.line_field_ids.filtered(
                lambda line: line.field_id and line.field_id.model_id != section.related_model_id
            )
            if wrong_fields:
                raise ValidationError(_("All line fields must belong to the One2many related model."))


class DynamicPdfReportLineField(models.Model):
    _name = "dynamic.pdf.report.line.field"
    _description = "Dynamic PDF Report Line Field"
    _order = "sequence, id"

    _sql_constraints = [
        (
            "unique_section_field",
            "unique(section_id, field_id)",
            "A line field can only be selected once in the same line section.",
        ),
    ]

    section_id = fields.Many2one(
        "dynamic.pdf.report.line.section",
        required=True,
        ondelete="cascade",
    )
    field_id = fields.Many2one(
        "ir.model.fields",
        required=True,
        ondelete="cascade",
        domain=[("ttype", "in", ALLOWED_FIELD_TYPES)],
    )
    field_name = fields.Char(related="field_id.name", store=True, readonly=True)
    field_description = fields.Char(related="field_id.field_description", store=True, readonly=True)
    field_type = fields.Selection(related="field_id.ttype", store=True, readonly=True)
    sequence = fields.Integer(default=10)
    show_label = fields.Boolean(default=True)

    @api.model_create_multi
    def create(self, vals_list):
        self._validate_unique_line_fields(vals_list)
        return super().create(vals_list)

    def write(self, vals):
        checks = []
        for line in self:
            checks.append({
                "section_id": vals.get("section_id", line.section_id.id),
                "field_id": vals.get("field_id", line.field_id.id),
                "line_id": line.id,
            })
        self._validate_unique_line_fields(checks)
        return super().write(vals)

    @api.model
    def _validate_unique_line_fields(self, vals_list):
        seen = set()
        for vals in vals_list:
            section_id = vals.get("section_id")
            field_id = vals.get("field_id")
            line_id = vals.get("line_id")
            if not section_id or not field_id:
                continue

            key = (section_id, field_id)
            if key in seen:
                raise ValidationError(_("A line field can only be selected once in the same line section."))
            seen.add(key)

            domain = [("section_id", "=", section_id), ("field_id", "=", field_id)]
            if line_id:
                domain.append(("id", "!=", line_id))
            if self.search_count(domain):
                raise ValidationError(_("A line field can only be selected once in the same line section."))

    @api.constrains("field_id", "section_id")
    def _check_field_id(self):
        for line in self:
            if not line.field_id or not line.section_id:
                continue
            if line.field_type not in ALLOWED_FIELD_TYPES:
                allowed_types = ", ".join(ALLOWED_FIELD_TYPES)
                raise ValidationError(_("Line sections support only these field types: %s", allowed_types))
            if line.section_id.related_model_id and line.field_id.model_id != line.section_id.related_model_id:
                raise ValidationError(_("The selected line field must belong to the One2many related model."))
